image:
  repository: 110425445190.dkr.ecr.us-east-1.amazonaws.com/insurenext-auth-service
  tag: 6f241d6
service:
  port: 8081
livenessProbe:
  path: /actuator/health/liveness
readinessProbe:
  path: /actuator/health/readiness
ingress:
  enabled: true
env:
  DB_HOST: "postgres-internal"
  DB_NAME: "insurenext_auth"
  DB_USER: "insurenext"
  DB_PASSWORD: "insurenext"
  JWT_SECRET: "day3-temporary-secret-change-this-later"
